"""SQLAlchemy 模型基类与通用约定（docs/06 §10 · docs/10 数据库设计）。

约定（本文件是全项目 schema 约定的唯一落点，改约定必须先改 docs/10 再改这里）：

1. **Alembic 唯一 schema 真源**：本 metadata 经 autogenerate 产出迁移；
   Java 侧 JPA 只做纯映射（``ddl-auto=none``），约束/FK/索引一律只在本 metadata 声明。
2. **JSONB 兼容**：业务 JSON 字段一律用 :func:`jsonb` 包装类型——PG 落 ``JSONB``、
   SQLite（单测 create_all）落 ``JSON``，避免 M2 建表后 SQLite 测试炸（docs/09 4.3）。
3. **主键**：``BIGINT GENERATED BY DEFAULT AS IDENTITY``（PG16）；显式 ID 插入仍合法
   （种子数据可能用到）；SQLite 单测兼容（已探针验证）。
4. **时间戳**：统一 ``timestamptz``（UTC）；``created_at`` 服务端默认 ``now()``；
   ``updated_at`` 由**各写方**在 UPDATE 时自行刷新（SQLAlchemy ``onupdate`` 只是本服务侧约定，
   Java 写方须以 ``@LastModifiedDate`` 或显式赋值保持一致——见 docs/10 §5 写归属契约）。
5. **枚举**：不建 PG 原生 ``ENUM``（autogenerate 漂移/重建坑、SQLite 不兼容），
   一律 ``VARCHAR`` + 显式命名的 ``CheckConstraint``（``ck_<表>_<语义名>``）。
6. **命名约定**：``naming_convention`` 保证约束/索引名确定，autogenerate 稳定、迁移可复现。
7. **删除策略**：业务表不做物理删除（user 只禁用、内容只上下架）；FK 除明细表
   （lrc/scores/scenario_messages 等随父级 CASCADE）外默认 RESTRICT（不写 ON DELETE）。
8. **写归属（Single Writer）**：每张表有且仅有一个服务具备 DB 写权（见 docs/10 §3 矩阵）；
   另一个服务只读；跨服务写通过内部 REST 委托（如 Python→Java 更新用户档位）。
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    DateTime,
    Identity,
    Integer,
    MetaData,
    func,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ---------------------------------------------------------------------------
# 命名约定（Alembic 官方推荐模板；约束名确定 → autogenerate/check 稳定）
# ---------------------------------------------------------------------------
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """全项目 Declarative Base（约定唯一落点）。"""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def jsonb() -> JSON:
    """业务 JSON 字段统一包装：PG=JSONB、SQLite=JSON（docs/06 §10 / docs/09 4.3）。

    用法：``details: Mapped[dict] = mapped_column(jsonb(), nullable=False, ...)``
    """
    return JSON().with_variant(postgresql.JSONB, "postgresql")


def bigint_pk() -> Mapped[int]:
    """BIGINT IDENTITY 主键（PG16 生成 BY DEFAULT，显式 ID 插入合法）。

    SQLite 变体 Integer：SQLite 只有 ``INTEGER PRIMARY KEY``（rowid 别名）才自增，
    纯 ``BIGINT`` 主键在单测插入时会报 NOT NULL（已探针验证）；PG 仍为 BIGINT。
    """
    return mapped_column(BigInteger().with_variant(Integer, "sqlite"), Identity(), primary_key=True)


class TimestampMixin:
    """可变行统一时间戳（created_at 服务端默认；updated_at 由写方维护）。"""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class CreatedAtMixin:
    """不可变行（消息/埋点/评分明细）：只记 created_at，不设 updated_at。"""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


# ---------------------------------------------------------------------------
# 枚举取值常量（单点维护；Java 映射为 @Enumerated(STRING) 字符串常量）
# ---------------------------------------------------------------------------
class Roles:
    USER = "user"
    ADMIN = "admin"


class UserStatus:
    ACTIVE = "active"
    DISABLED = "disabled"


class AgeGroups:
    CHILD = "child"
    TEEN = "teen"
    ADULT = "adult"
    SENIOR = "senior"


class Levels:
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"
    L4 = "L4"


class ContentStatus:
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class Channels:
    WEB = "web"
    PWA = "pwa"
    IOS = "ios"
    ANDROID = "android"
    OTHER = "other"


class PitchRefStatus:
    MISSING = "missing"
    BUILDING = "building"
    READY = "ready"
    INVALID = "invalid"


class PlacementQuestionKind:
    READ = "read"
    QA = "qa"


class LevelSources:
    PLACEMENT = "placement"
    MANUAL = "manual"


class SessionKinds:
    DIALOG = "dialog"
    SING = "sing"
    DEFENSE = "defense"  # 答辩会话（docs/14 §6.1，2026-09 拍板）
    SHADOW = "shadow"  # 影子跟读会话（local/31 §2.4，2026-09-02 设计）


class SessionStatus:
    ACTIVE = "active"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class MessageRoles:
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"


class AttemptKinds:
    DIALOG_SPEECH = "dialog_speech"
    FREE_PRACTICE = "free_practice"
    PLACEMENT_ITEM = "placement_item"
    DEFENSE_ANSWER = "defense_answer"  # 答辩作答（docs/14 §6.1，2026-09 拍板）
    SHADOW_SPEECH = "shadow_speech"  # 影子跟读录音（local/31 §2.4，2026-09-02 设计）


class DifficultySources:
    """素材难度来源（local/28 §4；local/31 §2.2）。推荐侧只看 diff_level/diff_score，不区分来源。"""

    EXPERT = "expert"  # 专家规则先验（样本 <30）
    BLEND = "blend"  # 先验+行为标定混合（30 ≤ n < 100）
    CALIBRATED = "calibrated"  # 行为主导（n ≥ 100，κ→1）


class MasteryStatus:
    """句级/场景级掌握度状态（local/29 §5.1）。"""

    NOT_MASTERED = "not_mastered"
    IN_PROGRESS = "in_progress"
    MASTERED = "mastered"


class EventTypes:
    """埋点事件类型（docs/06 §9.1 定稿 9 类 + corpus_hit 共 10 类）。

    新增须改本常量 + 迁移 + docs/06。
    """

    PAGE_VIEW = "page_view"
    SCENE_START = "scene_start"
    RECORDING_START = "recording_start"
    RECORDING_COMPLETE = "recording_complete"
    SCORE_EVENT = "score_event"
    RECOMMEND_IMPRESSION = "recommend_impression"
    RECOMMEND_CLICK = "recommend_click"
    PRACTICE_COMPLETE = "practice_complete"
    FUN_ACTION = "fun_action"
    CORPUS_HIT = "corpus_hit"  # 语言点覆盖度命中（docs/14 §6.3，2026-09 拍板）


class TicketStatuses:
    OPEN = "open"
    PROCESSING = "processing"
    RESOLVED = "resolved"
    CLOSED = "closed"
