"""initial schema (19 tables)

Revision ID: 0001
Revises:
Create Date: 2026-08-31

说明（docs/10-数据库设计.md · docs/11-数据库拷问报告.md）：
- 本迁移由模型层（app/models/，docs/06 §10 唯一 schema 真源）离线渲染生成 + 人工审阅修正；
- 修正点：① 时间戳 server_default 统一 CURRENT_TIMESTAMP（PG=now()，可移植）；
  ② 补回 autogenerate 跳过/忽略的两个表达式唯一索引（users.username/email 小写唯一）；
  ③ JSONB 字段沿用 JSON().with_variant(JSONB) 声明保证 SQLite 单测兼容；
  ④ 19 表 = docs/06 §10 清单 15 + 设计补充 4（song_pitch_refs / listening_materials /
     placement_questions / post_likes，依据 docs/11 Q-B06/Q-B13）。
- M2 接 PG 后首日：alembic upgrade head && alembic check（零 diff 门禁）；
  若 with_variant/表达式索引出噪音 diff，按 docs/11 Q-A04/Q-A05 处置。
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listening_materials",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("audio_url", sa.String(length=512), nullable=False),
        sa.Column("duration_s", sa.BigInteger(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column(
            "interest_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("license", sa.String(length=64), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('public_domain', 'original', 'demo_only') OR source IS NULL",
            name=op.f("ck_listening_materials_source"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_listening_materials_status"),
        ),
        sa.CheckConstraint("level BETWEEN 1 AND 4", name=op.f("ck_listening_materials_level")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listening_materials")),
    )
    op.create_index(
        "ix_listening_materials_status_level",
        "listening_materials",
        ["status", "level"],
        unique=False,
    )
    op.create_table(
        "placement_questions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("exam_revision", sa.SmallInteger(), nullable=False),
        sa.Column("item_index", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default=sa.text("'read'"), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("reference_answer", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'published'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('read', 'qa')", name=op.f("ck_placement_questions_kind")),
        sa.CheckConstraint(
            "status IN ('published', 'archived')", name=op.f("ck_placement_questions_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_questions")),
        sa.UniqueConstraint("exam_revision", "item_index", name="uq_placement_questions_rev_idx"),
    )
    op.create_index(
        "ix_placement_questions_revision", "placement_questions", ["exam_revision"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scope IN ('global', 'user', 'scene', 'song')", name=op.f("ck_reports_scope")
        ),
        sa.CheckConstraint("period_end >= period_start", name=op.f("ck_reports_period_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "report_type",
            "scope",
            "scope_id",
            "period_start",
            "period_end",
            name="uq_reports_scope_period",
        ),
    )
    op.create_index(
        "ix_reports_scope_period", "reports", ["scope", "scope_id", "period_start"], unique=False
    )
    op.create_table(
        "scenarios",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("scene_type", sa.String(length=32), nullable=False),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("opening_line", sa.Text(), nullable=False),
        sa.Column("target_corpus", sa.Text(), nullable=True),
        sa.Column(
            "interest_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("estimated_turns", sa.SmallInteger(), nullable=True),
        sa.Column("estimated_minutes", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scene_type IN ('cafe', 'airport', 'interview', 'library', 'other')",
            name=op.f("ck_scenarios_scene_type"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_scenarios_status")
        ),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 4", name=op.f("ck_scenarios_difficulty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
    )
    op.create_index("ix_scenarios_scene_type", "scenarios", ["scene_type"], unique=False)
    op.create_index("ix_scenarios_status_diff", "scenarios", ["status", "difficulty"], unique=False)
    op.create_table(
        "songs",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("artist", sa.String(length=128), nullable=True),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("duration_s", sa.BigInteger(), nullable=True),
        sa.Column("bpm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("musical_key", sa.String(length=8), nullable=True),
        sa.Column("audio_url", sa.String(length=512), nullable=False),
        sa.Column("lrc_url", sa.String(length=512), nullable=True),
        sa.Column("cover_url", sa.String(length=512), nullable=True),
        sa.Column(
            "interest_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.String(length=32),
            server_default=sa.text("'public_domain'"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "pitch_ref_status",
            sa.String(length=24),
            server_default=sa.text("'missing'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pitch_ref_status IN ('missing', 'building', 'ready', 'invalid')",
            name=op.f("ck_songs_pitch_ref_status"),
        ),
        sa.CheckConstraint(
            "source IN ('public_domain', 'original', 'demo_only')", name=op.f("ck_songs_source")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_songs_status")
        ),
        sa.CheckConstraint("level BETWEEN 1 AND 4", name=op.f("ck_songs_level")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_songs")),
    )
    op.create_index("ix_songs_status_level", "songs", ["status", "level"], unique=False)
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'user'"), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('user', 'admin')", name=op.f("ck_users_role")),
        sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f("ck_users_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    # 表达式唯一索引（autogenerate 不会自动带出，人工补；PG/SQLite 均支持）
    op.create_index("uq_users_username_lower", "users", [sa.text("lower(username)")], unique=True)
    op.create_index("uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True)

    op.create_table(
        "lrc",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("song_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("offset_ms", sa.BigInteger(), nullable=False),
        sa.Column("end_offset_ms", sa.BigInteger(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "source",
            sa.String(length=32),
            server_default=sa.text("'public_domain'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('public_domain', 'original', 'demo_only')", name=op.f("ck_lrc_source")
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], name=op.f("fk_lrc_song_id_songs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lrc")),
        sa.UniqueConstraint("song_id", "seq", name="uq_lrc_song_seq"),
    )
    op.create_table(
        "placements",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("exam_revision", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'in_progress'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pron_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("flu_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("gram_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("level", sa.String(length=8), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("level IN ('L1', 'L2', 'L3', 'L4')", name=op.f("ck_placements_level")),
        sa.CheckConstraint(
            "status IN ('in_progress', 'completed', 'abandoned')", name=op.f("ck_placements_status")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_placements_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placements")),
    )
    op.create_index(
        "ix_placements_user_started", "placements", ["user_id", "started_at"], unique=False
    )
    op.create_table(
        "post_likes",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("liker_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("practice_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_post_likes_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["liker_id"], ["users.id"], name=op.f("fk_post_likes_liker_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_likes")),
        sa.UniqueConstraint(
            "liker_id", "author_id", "practice_date", name="uq_post_likes_liker_author_date"
        ),
    )
    op.create_index(
        "ix_post_likes_author_date", "post_likes", ["author_id", "practice_date"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_index("uq_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=True)
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("scenario_id", sa.BigInteger(), nullable=True),
        sa.Column("song_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("turn_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "user_turn_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("assigned_turns", sa.SmallInteger(), nullable=True),
        sa.Column("duration_s", sa.BigInteger(), nullable=True),
        sa.Column("channel", sa.String(length=16), server_default=sa.text("'web'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('dialog', 'sing')", name=op.f("ck_sessions_kind")),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'abandoned')", name=op.f("ck_sessions_status")
        ),
        sa.CheckConstraint("turn_count >= 0", name=op.f("ck_sessions_turn_count")),
        sa.CheckConstraint("user_turn_count >= 0", name=op.f("ck_sessions_user_turn_count")),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.id"],
            name=op.f("fk_sessions_scenario_id_scenarios"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], name=op.f("fk_sessions_song_id_songs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index("ix_sessions_status_kind", "sessions", ["status", "kind"], unique=False)
    op.create_index("ix_sessions_user_started", "sessions", ["user_id", "started_at"], unique=False)
    op.create_table(
        "tickets",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=True),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("admin_id", sa.BigInteger(), nullable=True),
        sa.Column("admin_reply", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('feedback', 'bug', 'content_correction')", name=op.f("ck_tickets_kind")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'processing', 'resolved', 'closed')", name=op.f("ck_tickets_status")
        ),
        sa.CheckConstraint(
            "target_type IN ('scene', 'song', 'attempt', 'none') OR target_type IS NULL",
            name=op.f("ck_tickets_target_type"),
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], name=op.f("fk_tickets_admin_id_users")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_tickets_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tickets")),
    )
    op.create_index("ix_tickets_status_created", "tickets", ["status", "created_at"], unique=False)
    op.create_index("ix_tickets_user_id", "tickets", ["user_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "age_group", sa.String(length=16), server_default=sa.text("'adult'"), nullable=False
        ),
        sa.Column(
            "cefr_level", sa.String(length=8), server_default=sa.text("'L1'"), nullable=False
        ),
        sa.Column("learning_goal", sa.String(length=255), nullable=True),
        sa.Column(
            "interest_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "voice_rate", sa.String(length=16), server_default=sa.text("'normal'"), nullable=False
        ),
        sa.Column("voice_type", sa.String(length=32), nullable=True),
        sa.Column("preferred_difficulty", sa.SmallInteger(), nullable=True),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column(
            "cefr_level_source",
            sa.String(length=16),
            server_default=sa.text("'manual'"),
            nullable=False,
        ),
        sa.Column("cefr_level_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "age_group IN ('child', 'teen', 'adult', 'senior')",
            name=op.f("ck_user_profiles_age_group"),
        ),
        sa.CheckConstraint(
            "cefr_level IN ('L1', 'L2', 'L3', 'L4')", name=op.f("ck_user_profiles_cefr_level")
        ),
        sa.CheckConstraint(
            "cefr_level_source IN ('placement', 'manual')",
            name=op.f("ck_user_profiles_cefr_level_source"),
        ),
        sa.CheckConstraint(
            "voice_rate IN ('slow', 'normal', 'fast')", name=op.f("ck_user_profiles_voice_rate")
        ),
        sa.CheckConstraint(
            "preferred_difficulty BETWEEN 1 AND 4",
            name=op.f("ck_user_profiles_preferred_difficulty"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_profiles_user_id")),
    )
    op.create_table(
        "events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("session_id", sa.BigInteger(), nullable=True),
        sa.Column("browse_session_id", sa.String(length=36), nullable=True),
        sa.Column("recommend_group_id", sa.String(length=36), nullable=True),
        sa.Column("client_event_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_offset_ms", sa.BigInteger(), nullable=True),
        sa.Column("page", sa.String(length=64), nullable=True),
        sa.Column("target_type", sa.String(length=16), nullable=True),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column("age_group", sa.String(length=16), nullable=True),
        sa.Column("level", sa.String(length=8), nullable=True),
        sa.Column("scene_id", sa.BigInteger(), nullable=True),
        sa.Column("song_id", sa.BigInteger(), nullable=True),
        sa.Column("channel", sa.String(length=16), server_default=sa.text("'web'"), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "age_group IN ('child', 'teen', 'adult', 'senior') OR age_group IS NULL",
            name=op.f("ck_events_age_group"),
        ),
        sa.CheckConstraint(
            "channel IN ('web', 'pwa', 'ios', 'android', 'other')", name=op.f("ck_events_channel")
        ),
        sa.CheckConstraint(
            "event_type IN ('page_view', 'scene_start', 'recording_start', 'recording_complete', 'score_event', 'recommend_impression', 'recommend_click', 'practice_complete', 'fun_action')",
            name=op.f("ck_events_event_type"),
        ),
        sa.CheckConstraint(
            "level IN ('L1', 'L2', 'L3', 'L4') OR level IS NULL", name=op.f("ck_events_level")
        ),
        sa.CheckConstraint(
            "target_type IN ('scene', 'song', 'home') OR target_type IS NULL",
            name=op.f("ck_events_target_type"),
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["scenarios.id"], name=op.f("fk_events_scene_id_scenarios")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_events_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], name=op.f("fk_events_song_id_songs")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_events_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_age_type_occurred",
        "events",
        ["event_type", "age_group", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_events_browse_session", "events", ["browse_session_id", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_events_level_type_occurred",
        "events",
        ["event_type", "level", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_events_scene_type_occurred",
        "events",
        ["event_type", "scene_id", "occurred_at"],
        unique=False,
    )
    op.create_index("ix_events_session_id", "events", ["session_id"], unique=False)
    op.create_index(
        "ix_events_song_type_occurred",
        "events",
        ["event_type", "song_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_events_type_occurred", "events", ["event_type", "occurred_at"], unique=False
    )
    op.create_index("ix_events_user_occurred", "events", ["user_id", "occurred_at"], unique=False)
    op.create_index("uq_events_client_event_id", "events", ["client_event_id"], unique=True)
    op.create_table(
        "scenario_messages",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("origin", sa.String(length=24), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("audio_url", sa.String(length=512), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("prompt_version", sa.SmallInteger(), nullable=True),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('demo', 'correction', 'retry') OR action IS NULL",
            name=op.f("ck_scenario_messages_action"),
        ),
        sa.CheckConstraint(
            "origin IS NULL OR (role = 'user' AND origin IN ('proactive', 'respond'))",
            name=op.f("ck_scenario_messages_origin"),
        ),
        sa.CheckConstraint(
            "role IN ('system', 'user', 'assistant')", name=op.f("ck_scenario_messages_role")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_scenario_messages_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_messages")),
        sa.UniqueConstraint("session_id", "seq", name="uq_scenario_messages_session_seq"),
    )
    op.create_table(
        "sing_attempts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=True),
        sa.Column("song_id", sa.BigInteger(), nullable=False),
        sa.Column("lrc_id", sa.BigInteger(), nullable=True),
        sa.Column("audio_url", sa.String(length=512), nullable=True),
        sa.Column("duration_s", sa.SmallInteger(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pitch_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("rhythm_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pron_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("is_complete", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("expected_lines", sa.SmallInteger(), nullable=True),
        sa.Column(
            "lines",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "alignment",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lrc_id"], ["lrc.id"], name=op.f("fk_sing_attempts_lrc_id_lrc"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_sing_attempts_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], name=op.f("fk_sing_attempts_song_id_songs")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sing_attempts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sing_attempts")),
    )
    op.create_index("ix_sing_attempts_lrc_id", "sing_attempts", ["lrc_id"], unique=False)
    op.create_index("ix_sing_attempts_song_id", "sing_attempts", ["song_id"], unique=False)
    op.create_index(
        "ix_sing_attempts_user_created", "sing_attempts", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "song_pitch_refs",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("lrc_id", sa.BigInteger(), nullable=False),
        sa.Column("start_ms", sa.BigInteger(), nullable=False),
        sa.Column("end_ms", sa.BigInteger(), nullable=False),
        sa.Column(
            "pitch_ref",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "extractor", sa.String(length=32), server_default=sa.text("'pyin'"), nullable=False
        ),
        sa.Column("version", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lrc_id"], ["lrc.id"], name=op.f("fk_song_pitch_refs_lrc_id_lrc"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_song_pitch_refs")),
        sa.UniqueConstraint("lrc_id", name="uq_song_pitch_refs_lrc_id"),
    )
    op.create_table(
        "attempts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=True),
        sa.Column("scenario_message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "kind", sa.String(length=24), server_default=sa.text("'dialog_speech'"), nullable=False
        ),
        sa.Column("audio_url", sa.String(length=512), nullable=True),
        sa.Column("duration_s", sa.SmallInteger(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("pron_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("flu_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("gram_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("completeness", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wpm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "error",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('dialog_speech', 'free_practice', 'placement_item')",
            name=op.f("ck_attempts_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_message_id"],
            ["scenario_messages.id"],
            name=op.f("fk_attempts_scenario_message_id_scenario_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_attempts_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_attempts_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
    )
    op.create_index(
        "ix_attempts_scenario_message_id", "attempts", ["scenario_message_id"], unique=False
    )
    op.create_index("ix_attempts_session_id", "attempts", ["session_id"], unique=False)
    op.create_index("ix_attempts_user_created", "attempts", ["user_id", "created_at"], unique=False)
    op.create_table(
        "scores",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            nullable=False,
        ),
        sa.Column("attempt_id", sa.BigInteger(), nullable=False),
        sa.Column("word_index", sa.SmallInteger(), nullable=False),
        sa.Column("phoneme", sa.String(length=64), nullable=False),
        sa.Column("start_ms", sa.BigInteger(), nullable=True),
        sa.Column("end_ms", sa.BigInteger(), nullable=True),
        sa.Column("score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("is_key_word", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "error_type IN ('substitution', 'omission', 'insertion', 'mispronunciation', 'stress', 'intonation', 'other') OR error_type IS NULL",
            name=op.f("ck_scores_error_type"),
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_scores_attempt_id_attempts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint(
            "attempt_id", "word_index", "phoneme", name="uq_scores_attempt_word_phoneme"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # derived by reverse order of upgrade operations (docs/10 §7.1: 逆序幂等)
    op.drop_index("ix_attempts_user_created", table_name="attempts")
    op.drop_index("ix_attempts_session_id", table_name="attempts")
    op.drop_index("ix_attempts_scenario_message_id", table_name="attempts")
    op.drop_index("ix_sing_attempts_user_created", table_name="sing_attempts")
    op.drop_index("ix_sing_attempts_song_id", table_name="sing_attempts")
    op.drop_index("ix_sing_attempts_lrc_id", table_name="sing_attempts")
    op.drop_index("uq_events_client_event_id", table_name="events")
    op.drop_index("ix_events_user_occurred", table_name="events")
    op.drop_index("ix_events_type_occurred", table_name="events")
    op.drop_index("ix_events_song_type_occurred", table_name="events")
    op.drop_index("ix_events_session_id", table_name="events")
    op.drop_index("ix_events_scene_type_occurred", table_name="events")
    op.drop_index("ix_events_level_type_occurred", table_name="events")
    op.drop_index("ix_events_browse_session", table_name="events")
    op.drop_index("ix_events_age_type_occurred", table_name="events")
    op.drop_index("ix_tickets_user_id", table_name="tickets")
    op.drop_index("ix_tickets_status_created", table_name="tickets")
    op.drop_index("ix_sessions_user_started", table_name="sessions")
    op.drop_index("ix_sessions_status_kind", table_name="sessions")
    op.drop_index("uq_refresh_tokens_token_hash", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_index("ix_post_likes_author_date", table_name="post_likes")
    op.drop_index("ix_placements_user_started", table_name="placements")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_index("uq_users_username_lower", table_name="users")
    op.drop_index("ix_songs_status_level", table_name="songs")
    op.drop_index("ix_scenarios_status_diff", table_name="scenarios")
    op.drop_index("ix_scenarios_scene_type", table_name="scenarios")
    op.drop_index("ix_reports_scope_period", table_name="reports")
    op.drop_index("ix_placement_questions_revision", table_name="placement_questions")
    op.drop_index("ix_listening_materials_status_level", table_name="listening_materials")
    op.drop_table("scores")
    op.drop_table("attempts")
    op.drop_table("song_pitch_refs")
    op.drop_table("sing_attempts")
    op.drop_table("scenario_messages")
    op.drop_table("events")
    op.drop_table("user_profiles")
    op.drop_table("tickets")
    op.drop_table("sessions")
    op.drop_table("refresh_tokens")
    op.drop_table("post_likes")
    op.drop_table("placements")
    op.drop_table("lrc")
    op.drop_table("users")
    op.drop_table("songs")
    op.drop_table("scenarios")
    op.drop_table("reports")
    op.drop_table("placement_questions")
    op.drop_table("listening_materials")
